// Project Eulers

/*
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55

28 Divisors: 1, 2, 4, 7, 14, 28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over n divisors?
*/

function divisibleTriangleNumber(n) {

    let triangle = 0
    for (let i = 1; i > 0; i++) {
        triangle += i
        if (divisorCount(triangle) > n) {
            i = -1
            continue
        }
    }
    return triangle
}

function divisorCount(num) {
    let count = 2
    let end = num
    for (let i = 2; i < end; i++) {
        if (num % i === 0) {
            count += 2
            end = num / i
            continue
        }
    }
    return count
}

console.log(divisibleTriangleNumber(23));
